### ISSUE TITLE
Incorrect instruction to access 'Getting Started'

### ISSUE THREAD

**Issue by hfreund** [auth0-training/labs-node-working-with-connections#11]
### Description

In Code Tour Step 3 or 7 (1: Working With Connections), the second instruction says to:
> Remind yourself what the current login experience looks like by clicking the profile image in the upper right hand corner and selecting Getting Started > "Try your login box" > Try it out.

The accompanying gif shows the same interaction. 

On my developer tenant I do not see 'Getting Started' in the user menu, instead I see it at the top of left navigation
<img width="329" alt="Screenshot 2024-07-12 at 4 38 00 PM" src="https://github.com/user-attachments/assets/06f445f9-0209-4773-a42e-54a39eea843f">

### Reproduction

1. Login to Auth0
2. Select the development tenant
3. Click the user menu -> observe there is no link for 'Getting Started'
4. Look at the left side navigation and see the first link says 'Getting Started'
5. Click 'Getting Started' in the left side navigation and see the content of the page matches the content shown in the Code Tour gif

### Environment

- **Version of this library used:** Unversioned. Accessed on 07-12-2024, last commit on 07-02-2024
- **Version of the platform or framework used, if applicable:** Unknown
- **Other relevant versions (language, server software, OS, browser):** Chrome, MacOS
- **Other modules/plugins/libraries that might be involved:**

**Comment by vbravo821** [comment]
Updated instructions.

**Comment by kazemicode** [comment]
Closed by #12
